# Generated by Django 4.0.3 on 2023-05-23 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pybo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='view_count',
            field=models.IntegerField(default=0),
        ),
    ]
