# Generated by Django 4.0.3 on 2023-05-23 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pybo', '0004_question_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='price',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
